# Generated by Django 6.0 on 2026-04-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('ingredient', 'Ingredient'), ('prepared', 'Prepared')], default='simple', max_length=16),
        ),
    ]
