# Generated by Django 6.0 on 2025-12-26 11:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
    ]
