# Generated by Django 6.0 on 2026-02-06 00:01

import uuid
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("sku", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("barcode", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("unit_price", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("status", models.CharField(choices=[("active", "Active"), ("archived", "Archived")], default="active", max_length=16)),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="products.product"),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("product", "name"),
                        name="uniq_active_variant_name_per_product",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("sku__gt", "")),
                        fields=("product", "sku"),
                        name="uniq_variant_sku_per_product",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("barcode__gt", "")),
                        fields=("product", "barcode"),
                        name="uniq_variant_barcode_per_product",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductAddon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("price", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("status", models.CharField(choices=[("active", "Active"), ("archived", "Archived")], default="active", max_length=16)),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="addons", to="products.product"),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("product", "name"),
                        name="uniq_active_addon_name_per_product",
                    ),
                ],
            },
        ),
    ]
