# Generated by Django 6.0 on 2026-02-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_variants_addons'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='uniq_active_category_name_per_org',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
