# Generated by Django 6.0 on 2026-01-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_kitchen_ticket'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kitchenticket',
            new_name='orders_kitc_org_id_813a98_idx',
            old_name='orders_kitc_org_id_7aeb8b_idx',
        ),
    ]
