# Generated by Django 6.0 on 2025-12-28 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_subtotal_order_tax_total_order_total'),
        ('orgs', '0003_orgnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('from_status', models.CharField(max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='orders.order')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_status_events', to='orgs.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'order', 'created_at'], name='orders_orde_org_id_5adbd9_idx'), models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_1e3f4d_idx')],
            },
        ),
    ]
