# Generated by Django 6.0 on 2026-04-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=16)),
                ('logger_name', models.CharField(blank=True, default='', max_length=128)),
                ('event', models.CharField(blank=True, default='', max_length=128)),
                ('message', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('org_id', models.CharField(blank=True, default='', max_length=64)),
                ('user_id', models.CharField(blank=True, default='', max_length=64)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('method', models.CharField(blank=True, default='', max_length=16)),
                ('task_id', models.CharField(blank=True, default='', max_length=64)),
                ('task_name', models.CharField(blank=True, default='', max_length=255)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['org_id', 'created_at'], name='logs_dashbo_org_id_00b435_idx'), models.Index(fields=['level', 'created_at'], name='logs_dashbo_level_265eef_idx'), models.Index(fields=['request_id'], name='logs_dashbo_request_c17f40_idx')],
            },
        ),
    ]
