# Generated by Django 6.0 on 2026-02-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='logentry',
            new_name='logs_dashbo_org_id_00b435_idx',
            old_name='logs_dash_org_id_8fd1b0_idx',
        ),
        migrations.RenameIndex(
            model_name='logentry',
            new_name='logs_dashbo_level_265eef_idx',
            old_name='logs_dash_level_2fe9f4_idx',
        ),
        migrations.RenameIndex(
            model_name='logentry',
            new_name='logs_dashbo_request_c17f40_idx',
            old_name='logs_dash_request_8b0c8f_idx',
        ),
    ]
