# Generated by Django 6.0 on 2026-04-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountingentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("sale", "Продажа"),
                    ("refund", "Возврат"),
                    ("stock_receipt", "Приход товара"),
                    ("payment_out", "Оплата поставщику"),
                ],
                max_length=32,
            ),
        ),
    ]
