# Generated by Django 6.0 on 2026-04-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_alter_accountingentry_entry_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingentry",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
