# Generated by Django 6.0 on 2026-04-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0003_accountingentry_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingentry",
            name="export_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает экспорта"),
                    ("exported", "Экспортировано"),
                    ("failed", "Ошибка экспорта"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="accountingentry",
            name="exported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
