# Generated by Django 6.0 on 2026-04-04 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_accountingentry_export_status_and_more'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingentry',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_entries', to='partners.partner'),
        ),
    ]
