# Generated by Django 6.0 on 2026-04-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_accountingentry_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingentry',
            name='entry_type',
            field=models.CharField(choices=[('sale', 'Продажа'), ('refund', 'Возврат'), ('stock_receipt', 'Приход товара'), ('stock_out', 'Расход товара'), ('payment_out', 'Оплата поставщику')], max_length=32),
        ),
    ]
