# Generated by Django 6.0 on 2026-04-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_accountingentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingentry',
            name='entry_type',
            field=models.CharField(choices=[('sale', 'Продажа'), ('refund', 'Возврат'), ('refund_cash', 'Возврат наличными'), ('refund_card', 'Возврат по карте'), ('stock_receipt', 'Приход товара'), ('stock_out', 'Расход товара'), ('payment_out', 'Оплата поставщику'), ('sale_cash', 'Продажа наличными'), ('sale_card', 'Продажа картой'), ('cash_in', 'Внесение наличных'), ('cash_out', 'Изъятие наличных')], max_length=32),
        ),
    ]
