"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', cast=bool)

ALLOWED_HOSTS = config('DJANGO_ALLOWED_HOSTS', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',

    'config.users',
    "config.dictionaries",
    "config.orgs",
    
    "apps.partners",
    "apps.products",
    "apps.orders",
    "apps.payments",
    "apps.cashier",
    "apps.ops_dashboard",

]

AUTH_USER_MODEL = "users.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

DEFAULT_CURRENCY = config("DEFAULT_CURRENCY", default="EUR")
CASHIER_DEVICE_TOKEN = config("CASHIER_DEVICE_TOKEN", default="")
LOGIN_URL = "/cashier/login/"



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRES_DB'),
        'USER': config('POSTGRES_USER'),
        'PASSWORD': config('POSTGRES_PASSWORD'),
        'HOST': config('POSTGRES_HOST', default='db'),
        'PORT': config('POSTGRES_PORT', default='5432'),
        'CONN_MAX_AGE': 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Celery + Redis (async task processing + device command streaming).
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://redis:6379/0")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="redis://redis:6379/1")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
# Keep device streaming in a dedicated queue so workers can be scaled independently.
CELERY_TASK_ROUTES = {
    "apps.payments.tasks.dispatch_device_commands": {"queue": "device_commands"},
    "apps.payments.tasks.dispatch_device_commands_for_all_orgs": {"queue": "device_commands"},
    "apps.payments.tasks.process_device_commands_mock": {"queue": "device_commands"},
    "apps.payments.tasks.process_device_commands_mock_for_all_orgs": {"queue": "device_commands"},
}

CELERY_BEAT_SCHEDULE = {
    "dispatch-device-commands-all-orgs": {
        "task": "apps.payments.tasks.dispatch_device_commands_for_all_orgs",
        "schedule": 60.0,
        "kwargs": {"limit": 50},
    },
}

# Redis stream settings for device command delivery.
DEVICE_COMMANDS_REDIS_URL = config("DEVICE_COMMANDS_REDIS_URL", default=CELERY_BROKER_URL)
DEVICE_COMMANDS_STREAM = config("DEVICE_COMMANDS_STREAM", default="device_commands")
DEVICE_COMMANDS_STREAM_MAXLEN = config("DEVICE_COMMANDS_STREAM_MAXLEN", cast=int, default=10000)
DEVICE_COMMANDS_RETRY_BASE_SECONDS = config(
    "DEVICE_COMMANDS_RETRY_BASE_SECONDS", cast=int, default=10
)
DEVICE_COMMANDS_RETRY_MAX_SECONDS = config(
    "DEVICE_COMMANDS_RETRY_MAX_SECONDS", cast=int, default=300
)

# Mock fiscal agent (dev/staging).
FISCAL_MOCK_ENABLED = config("FISCAL_MOCK_ENABLED", cast=bool, default=False)
FISCAL_MOCK_OFFLINE = config("FISCAL_MOCK_OFFLINE", cast=bool, default=False)

if FISCAL_MOCK_ENABLED:
    CELERY_BEAT_SCHEDULE["mock-device-commands-all-orgs"] = {
        "task": "apps.payments.tasks.process_device_commands_mock_for_all_orgs",
        "schedule": 5.0,
        "kwargs": {"limit": 50},
    }


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
