# Generated by Django 6.0 on 2025-12-28 17:13

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_initial'),
        ('orgs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tender', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('prepaid_external', 'Prepaid external')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('refunded', 'Refunded'), ('voided', 'Voided'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('external_id', models.CharField(blank=True, max_length=128, null=True)),
                ('provider', models.CharField(default='manual', max_length=64)),
                ('raw_provider_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orgs.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminals', to='orgs.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32, null=True)),
                ('to_status', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_events', to='orgs.organization')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.orderpayment')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.terminal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='orderpayment',
            constraint=models.UniqueConstraint(fields=('org', 'idempotency_key'), name='uniq_payment_org_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='orderpayment',
            constraint=models.UniqueConstraint(fields=('org', 'external_id'), name='uniq_payment_org_external_id'),
        ),
    ]
