# Generated by Django 6.0 on 2026-04-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderpayment",
            name="failure_reason",
            field=models.TextField(blank=True, default="", max_length=255),
        ),
    ]
