# Generated by Django 6.0 on 2025-12-28 17:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_paymentevent_public_id(apps, schema_editor):
    PaymentEvent = apps.get_model("payments", "PaymentEvent")

    # Заполняем только те строки, где public_id ещё NULL.
    # Делаем через update_fields, чтобы не трогать остальное.
    for ev in PaymentEvent.objects.filter(public_id__isnull=True).only("id"):
        ev.public_id = uuid.uuid4()
        ev.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0002_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        # 1) Добавляем public_id как nullable и БЕЗ unique, чтобы миграция прошла на существующих строках.
        migrations.AddField(
            model_name="paymentevent",
            name="public_id",
            field=models.UUIDField(null=True, editable=False),
        ),

        # 2) Заполняем существующие строки уникальными UUID.
        migrations.RunPython(backfill_paymentevent_public_id, migrations.RunPython.noop),

        # 3) Делаем поле обязательным и уникальным.
        migrations.AlterField(
            model_name="paymentevent",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),

        # Это поля из OrgScopedModel (их добавление безопасно).
        migrations.AddField(
            model_name="paymentevent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="terminal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),

        # Приводим org FK к единому виду из OrgScopedModel
        migrations.AlterField(
            model_name="orderpayment",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="orgs.organization",
            ),
        ),
        migrations.AlterField(
            model_name="paymentevent",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="orgs.organization",
            ),
        ),
        migrations.AlterField(
            model_name="terminal",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="orgs.organization",
            ),
        ),
    ]
