# Generated by Django 6.0 on 2026-01-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_cash_drawer_movement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cashdrawermovement',
            new_name='payments_ca_session_3c4599_idx',
            old_name='payments_ca_session_5f0b3b_idx',
        ),
    ]
