# Generated by Codex on 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_rename_payments_ca_session_5f0b3b_idx_payments_ca_session_3c4599_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpayment",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="orderpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("org", "idempotency_key"),
                name="uniq_payment_idempotency_per_org",
            ),
        ),
    ]
