# Generated by Codex on 2026-01-27

from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_orderpayment_idempotency"),
        ("orders", "0004_rename_orders_kitc_org_id_7aeb8b_idx_orders_kitc_org_id_813a98_idx"),
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("receipt_type", models.CharField(choices=[("sale", "Sale"), ("refund", "Refund"), ("storno", "Storno"), ("cash_in", "Cash in"), ("cash_out", "Cash out")], max_length=16)),
                ("total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("tax_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="fiscal_receipts", to="orders.order")),
                ("org", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fiscal_receipts", to="orgs.organization")),
                ("payment", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="fiscal_receipt", to="payments.orderpayment")),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
