# Generated by Codex on 2026-01-27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_fiscal_receipt"),
        ("orders", "0004_rename_orders_kitc_org_id_7aeb8b_idx_orders_kitc_org_id_813a98_idx"),
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceCommand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("command_type", models.CharField(choices=[("fiscalize_sale", "Fiscalize sale"), ("print_kot", "Print kitchen order ticket"), ("print_receipt", "Print customer receipt"), ("payment_capture", "Capture payment")], max_length=32)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("sent", "Sent"), ("acked", "Acknowledged"), ("failed", "Failed")], default="pending", max_length=16)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("retries", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=5)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="device_commands", to="orders.order")),
                ("org", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="device_commands", to="orgs.organization")),
                ("payment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="device_commands", to="payments.orderpayment")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="devicecommand",
            constraint=models.UniqueConstraint(fields=("org", "idempotency_key"), name="uniq_device_command_idempotency_per_org"),
        ),
    ]
