# Generated by Codex on 2026-01-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0006_device_command"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiscalreceipt",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fiscal_receipts",
                to="payments.orderpayment",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalreceipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("payment__isnull", False)),
                fields=("payment", "receipt_type"),
                name="uniq_fiscal_receipt_per_payment_type",
            ),
        ),
    ]
