# Generated by Django 6.0 on 2026-01-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_fiscal_receipt_payment_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecommand',
            name='command_type',
            field=models.CharField(choices=[('fiscalize_sale', 'Fiscalize sale'), ('fiscalize_refund', 'Fiscalize refund'), ('print_kot', 'Print kitchen order ticket'), ('print_receipt', 'Print customer receipt'), ('payment_capture', 'Capture payment')], max_length=32),
        ),
    ]
