# Generated by Django 6.0 on 2026-04-01 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("equipment", "0001_initial"),
        ("inventory", "0001_initial"),
        ("orgs", "0001_initial"),
        ("partners", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocklot",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="stock_lots", to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="stocklot",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_lots",
                to="partners.partner",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="movements", to="inventory.stocklot"
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)ss", to="orgs.organization"
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="stock_movements", to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="storage_locations",
                to="equipment.equipment",
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)ss", to="orgs.organization"
            ),
        ),
        migrations.AddField(
            model_name="stocklot",
            name="storage_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_lots",
                to="inventory.storagelocation",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["org", "product", "movement_type"], name="inventory_s_org_id_f8304d_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["org", "lot", "created_at"], name="inventory_s_org_id_1a518e_idx"),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="stock_movement_quantity_gt_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="storagelocation",
            constraint=models.UniqueConstraint(fields=("org", "name"), name="uniq_storage_location_name_per_org"),
        ),
        migrations.AddIndex(
            model_name="stocklot",
            index=models.Index(fields=["org", "product", "status"], name="inventory_s_org_id_29dc69_idx"),
        ),
        migrations.AddIndex(
            model_name="stocklot",
            index=models.Index(fields=["org", "expires_at"], name="inventory_s_org_id_b47c02_idx"),
        ),
        migrations.AddConstraint(
            model_name="stocklot",
            constraint=models.CheckConstraint(
                condition=models.Q(("initial_qty__gt", 0)), name="stock_lot_initial_qty_gt_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklot",
            constraint=models.CheckConstraint(
                condition=models.Q(("remaining_qty__gte", 0)), name="stock_lot_remaining_qty_gte_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklot",
            constraint=models.CheckConstraint(
                condition=models.Q(("remaining_qty__lte", models.F("initial_qty"))),
                name="stock_lot_remaining_qty_lte_initial_qty",
            ),
        ),
    ]
