# Generated by Django 6.0 on 2026-03-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orgs', '0001_initial'),
        ('partners', '0001_initial'),
        ('products', '0007_remove_category_uniq_active_category_name_per_org_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklot',
            options={'ordering': ['received_at', 'id']},
        ),
        migrations.RenameField(
            model_name='stocklot',
            old_name='unit_price',
            new_name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='stocklot',
            name='produced_at',
        ),
        migrations.AddField(
            model_name='stocklot',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.CheckConstraint(condition=models.Q(('initial_qty__gt', 0)), name='stock_lot_initial_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_qty__gte', 0)), name='stock_lot_remaining_qty_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_qty__lte', models.F('initial_qty'))), name='stock_lot_remaining_qty_lte_initial_qty'),
        ),
    ]
