from .base import *  # noqa: F403

DEBUG = False

# HTTPS security settings
SECURE_HSTS_SECONDS = 300  # 5 минут
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True