# Generated by Django 6.0 on 2026-04-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeitem',
            name='unit',
        ),
    ]
