# Generated by Django 6.0 on 2026-04-07 16:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_remove_recipeitem_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))]
            ),
        ),
    ]
